### ISSUE TITLE
Shadow from buttons has strange color on black background

### ISSUE THREAD

**Issue by kchibisov** [Smithay/client-toolkit#102]
![picture](https://user-images.githubusercontent.com/27620401/74172758-d2b6c500-4c41-11ea-8b6b-9051b7d78a8c.png)

Format of colors is ARGB.

```yml
colors:
  primary_color: 0xff101010,
  secondary_color: 0xffffffff,
  close_button_color: 0xff101010,
  close_button_icon_color: 0xffffffff,
  maximize_button_color: 0xff101010,
  maximize_button_icon_color: 0xffffffff,
  minimize_button_color: 0xff101010,
  minimize_button_icon_color: 0xffffffff,
```
Close button has strange colors due to winit bug, but maximize and minimize buttons should reflect current SCTK behavior.
